homepage: "http://www.postfix.org/"
language: c
fuzzing_engines:
- afl
sanitizers:
- address
primary_contact: "wietse@gmail.com"
main_repo: "https://github.com/vdukhovni/postfix"
auto_ccs:
  - "david@adalogics.com"
