name: CIFuzz
on:
  push:
    branches:
      - master
  
      
  pull_request:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest    
     
    steps:
    
      - uses: actions/checkout@v2
        name: Check out code
        
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: khushi2/oss-fuzz
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  Fuzzing:
   runs-on: ubuntu-latest
   concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
   
   strategy:
        fail-fast: false
        matrix:
            sanitizer: 
              - address
            engine:
               - afl
            architecture:
              - x86_64
            include:
              - engine: afl
                sanitizer: address
                architecture: x86_64
                
   env:
      engine: afl
      SANITIZER: address
      ARCHITECTURE: x86_64
      
   
   steps:
     - uses: actions/checkout@v3
     
      
     - name: Build Fuzzers (${{ matrix.sanitizer }})
       id: build
       uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
       with:
        engine: afl
        github-token: ${{ secrets.TOKEN }}    
        language: c
        dry-run: false
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: true
        keep-unaffected-fuzz-targets: true
     
        
     - name: Run Fuzzers (${{ matrix.sanitizer }})
       uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
       with:
        engine: afl
        github-token: ${{ secrets.TOKEN }}
        language: c
        fuzz-seconds: 800
        mode: 'batch'
        dry-run: false
        report-unreproducible-crashes: true
        keep-unaffected-fuzz-targets: true
        sanitizer: ${{ matrix.sanitizer }} 
        
     - name: Compile and Fuzz
       run: |
            ./afl-cc -fsanitize=address,undefined -ggdb fuzz_mime.c -o fuzzer
            ./afl-fuzz -i in -o out -m none -- ./fuzzer @@
       
        
        
        
