name: CIFuzz
on:
  push:
    branches:
      - master
  
      
  pull_request:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest    
     
    steps:
        
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: khushi2/oss-fuzz
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          
  Fuzzing:
   runs-on: ubuntu-latest
   concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
   
   strategy:
        fail-fast: false
        matrix:
            sanitizer: 
              - address
            engine:
              - afl
            architecture:
              - x86_64
            include:
              - engine: afl
                sanitizer: address
                architecture: x86_64
                
   env:
      ENGINE: ${{ matrix.engine }}
      SANITIZER: ${{ matrix.sanitizer }}
      ARCHITECTURE: ${{ matrix.architecture }}
      
   
   steps:
     - uses: actions/checkout@v3
     - name: configure
       run: ./configure
     - name: make
       run: make
     - name: make check
       run: make check
     - name: make distcheck
       run: make distcheck
      
     - name: Build Fuzzers (${{ matrix.sanitizer }})
       id: build
       uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
       with:
        github-token: ${{ secrets.TOKEN }}    
        language: c
        dry-run: false
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: true
        keep-unaffected-fuzz-targets: true
     
        
     - name: Run Fuzzers (${{ matrix.sanitizer }})
       uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
       with:
        github-token: ${{ secrets.TOKEN }}
        language: c
        fuzz-seconds: 800
        mode: 'batch'
        dry-run: false
        report-unreproducible-crashes: true
        keep-unaffected-fuzz-targets: true
        sanitizer: ${{ matrix.sanitizer }}
      
